accelerate launch main.py --mode test \
    --seed 42 \
    --data_path Dataset \
    --data testgeneval \
    --baseline_prompt graph \
    --llm_model "HuggingFaceTB/SmolLM2-135M-Instruct" \
    --max_seq_len 16384 \
    --batch_size 1 \
    --gradient_accumulation_steps 16 \
    --save_steps 1000 \
    --validating_steps 1000 \
    --num_gpu 1 \
    --name "testing_small_graph_accelerate" \
    --output_dir "./results/models/" \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --n_hidden 16 \
    --learning_rate 5e-5 \
    --max_grad_norm 1.0 \
    --num_train_epochs 3 \
    --dtype bfloat16 \
    --use_lora \
    --use_accelerate \
    --graph_sampling \
    --model_weight_path results/models/testing_small_graph_accelerate/final_model \
    --do_test