accelerate launch --num_processes 2 main.py --mode train \
    --seed 42 \
    --data_path Dataset \
    --data testgeneval \
    --baseline_prompt graph \
    --llm_model "Qwen/CodeQwen1.5-7B-Chat" \
    --max_seq_len 16384 \
    --batch_size 1 \
    --gradient_accumulation_steps 1 \
    --num_gpu 2 \
    --output_dir "./results/models/" \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --learning_rate 5e-5 \
    --max_grad_norm 1.0 \
    --num_train_epochs 1 \
    --dtype bfloat16 \
    --debug \
    --use_lora

export CUDA_VISIBLE_DEVICES=0

accelerate launch --debug --num_processes 4  main.py --mode train \
    --seed 42 \
    --data_path Dataset \
    --data testgeneval \
    --baseline_prompt graph_tr \
    --llm_model "Qwen/Qwen2.5-Coder-7B" \
    --max_seq_len 28000 \
    --batch_size 1 \
    --gradient_accumulation_steps 4 \
    --save_steps 16 \
    --validating_steps 1000 \
    --num_gpu 4 \
    --model_name "qwen2_5-7b"\
    --name "testing_qwen25_7b_graph_tr_accelerate" \
    --output_dir "./results/models/" \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --n_hidden 16 \
    --learning_rate 1e-4 \
    --max_grad_norm 1.0 \
    --num_train_epochs 1 \
    --dtype bf16 \
    --use_lora \
    --lora_r 32 \
    --use_accelerate \
    --graph_sampling

accelerate launch --debug --num_processes 1  main.py --mode train \
    --seed 42 \
    --data_path Dataset \
    --data testgeneval \
    --baseline_prompt graph_tr \
    --llm_model "Qwen/Qwen2.5-Coder-7B-Instruct" \
    --max_seq_len 28000 \
    --batch_size 1 \
    --gradient_accumulation_steps 4 \
    --save_steps 16 \
    --validating_steps 1000 \
    --num_gpu 1 \
    --model_name "qwen2_5-7b"\
    --name "testing_qwen25_7b_graph_tr_accelerate" \
    --output_dir "./results/models/" \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --n_hidden 16 \
    --learning_rate 1e-4 \
    --max_grad_norm 1.0 \
    --num_train_epochs 1 \
    --dtype bf16 \
    --use_lora \
    --lora_r 32 \
    --use_accelerate \
    --graph_sampling

accelerate launch --debug --num_processes 4  main.py --mode train \
    --seed 42 \
    --data_path Dataset \
    --data testgeneval \
    --baseline_prompt graph_tr \
    --llm_model "Qwen/Qwen2.5-Coder-7B-Instruct" \
    --max_seq_len 28000 \
    --batch_size 1 \
    --gradient_accumulation_steps 32 \
    --save_steps 320 \
    --validating_steps 5000 \
    --num_gpu 4 \
    --model_name "qwen2_5-7b"\
    --name "qwen25_7b_graph_tr_3_epochs" \
    --output_dir "./results/models/" \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --n_hidden 16 \
    --learning_rate 5e-5 \
    --max_grad_norm 1.0 \
    --num_train_epochs 3 \
    --dtype bf16 \
    --use_lora \
    --lora_r 32 \
    --use_accelerate \
    --graph_sampling 
    
accelerate launch --debug --num_processes 1  main.py --mode train \
    --seed 42 \
    --data_path Dataset \
    --data testgeneval \
    --baseline_prompt graph_tr \
    --llm_model "Qwen/Qwen2.5-Coder-3B-Instruct" \
    --max_seq_len 28000 \
    --batch_size 1 \
    --gradient_accumulation_steps 32 \
    --save_steps 1000 \
    --validating_steps 5000 \
    --num_gpu 1 \
    --model_name "qwen2_5-3b"\
    --name "qwen25_3b_inst_graph_tr_1_epochs" \
    --output_dir "./results/models/" \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --lora_r 32 \
    --n_hidden 16 \
    --learning_rate 5e-5 \
    --max_grad_norm 1.0 \
    --num_train_epochs 1 \
    --dtype bf16 \
    --use_lora \
    --use_accelerate \
    --graph_sampling


accelerate launch --debug --num_processes 4  main.py --mode test \
    --seed 42 \
    --data_path Dataset \
    --data testgeneval \
    --baseline_prompt graph_tr \
    --llm_model "Qwen/Qwen2.5-Coder-7B-Instruct" \
    --max_seq_len 28000 \
    --batch_size 1 \
    --gradient_accumulation_steps 32 \
    --save_steps 320 \
    --validating_steps 5000 \
    --num_gpu 4 \
    --model_name "qwen2_5-7b"\
    --name "testing_qwen25_7b_graph_tr_accelerate" \
    --output_dir "./results/models/" \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --n_hidden 16 \
    --learning_rate 1e-4 \
    --max_grad_norm 1.0 \
    --num_train_epochs 1 \
    --dtype bf16 \
    --use_lora \
    --lora_r 32 \
    --use_accelerate \
    --model_weight_path "./results/models/qwen25_7b_graph_tr_3_epochs/current_checkpoint" \
    --graph_sampling

accelerate launch --debug --num_processes 1  main.py --mode data \
    --seed 42 \
    --data_path Dataset \
    --data testgeneval \
    --num_gpu 1 \
    --joern_port 2605 \
    --do_test \
    --do_crawl \
    --do_process_raw \
    --debug


accelerate launch --debug --num_processes 2  main.py --mode train \
    --seed 42 \
    --data_path Dataset \
    --data testgeneval \
    --baseline_prompt graph_tr \
    --llm_model "Qwen/Qwen2.5-Coder-3B" \
    --max_seq_len 32768 \
    --batch_size 1 \
    --gradient_accumulation_steps 16 \
    --save_steps 1000 \
    --validating_steps 2000 \
    --num_gpu 2 \
    --model_name "qwen2_5-3b"\
    --name "testing_qwen25_15_graph_tr_accelerate" \
    --output_dir "./results/models/" \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --n_hidden 16 \
    --learning_rate 5e-5 \
    --max_grad_norm 1.0 \
    --num_train_epochs 3 \
    --dtype bf16 \
    --use_lora \
    --use_accelerate \
    --graph_sampling \
    --do_test \
    --debug


accelerate launch --debug --num_processes 4  main.py --mode test \
    --seed 42 \
    --data_path Dataset \
    --data testgeneval \
    --baseline_prompt graph_tr \
    --llm_model "Qwen/Qwen2.5-Coder-7B-Instruct" \
    --max_seq_len 28000 \
    --batch_size 1 \
    --gradient_accumulation_steps 32 \
    --save_steps 320 \
    --validating_steps 5000 \
    --num_gpu 4 \
    --model_name "qwen2_5-7b"\
    --name "qwen25_7b_inst_graph_tr_3_epochs_temp" \
    --output_dir "./results/models/" \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --n_hidden 16 \
    --learning_rate 1e-4 \
    --max_grad_norm 1.0 \
    --num_train_epochs 1 \
    --dtype bf16 \
    --use_lora \
    --lora_r 32 \
    --use_accelerate \
    --model_weight_path "./results/models/qwen25_7b_graph_tr_3_epochs/current_checkpoint" \
    --graph_sampling

accelerate launch --debug --num_processes 4  main.py --mode train \
    --seed 42 \
    --data_path Dataset \
    --data testgeneval \
    --baseline_prompt graph_tr \
    --llm_model "Qwen/Qwen2.5-Coder-7B-Instruct" \
    --max_seq_len 28000 \
    --batch_size 1 \
    --gradient_accumulation_steps 32 \
    --save_steps 320 \
    --validating_steps 5000 \
    --num_gpu 4 \
    --model_name "qwen2_5-7b"\
    --name "qwen25_7b_graph_tr_3_epochs" \
    --output_dir "./results/models/" \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --n_hidden 16 \
    --learning_rate 1e-4 \
    --max_grad_norm 1.0 \
    --num_train_epochs 3 \
    --dtype bf16 \
    --use_lora \
    --lora_r 32 \
    --use_accelerate \
    --graph_sampling \
    --continue_training \
    --checkpoint_path "results/models/qwen25_7b_graph_tr_3_epochs/current_checkpoint/checkpoint-106880.pt"


CUDA_VISIBLE_DEVICES=1,2 accelerate launch --debug --num_processes 2  main.py --mode train \
    --seed 42 \
    --data_path Dataset \
    --data testgeneval \
    --baseline_prompt graph_tr \
    --llm_model "Qwen/Qwen2.5-Coder-1.5B-Instruct" \
    --max_seq_len 8196 \
    --batch_size 1 \
    --gradient_accumulation_steps 16 \
    --save_steps 100 \
    --validating_steps 1000 \
    --num_gpu 2 \
    --model_name "qwen2_5-1_5b"\
    --name "debugging_qwen25_1-5b_graph_tr_1_epochs" \
    --output_dir "./results/models/" \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --n_hidden 16 \
    --learning_rate 5e-5 \
    --max_grad_norm 1.0 \
    --num_train_epochs 1 \
    --dtype bf16 \
    --use_lora \
    --lora_r 4 \
    --use_accelerate \
    --graph_sampling 


python main.py --mode train \
    --seed 42 \
    --data_path Dataset \
    --data testgeneval \
    --baseline_prompt graph_tr \
    --llm_model "Qwen/Qwen2.5-Coder-1.5B-Instruct" \
    --max_seq_len 8196 \
    --batch_size 1 \
    --gradient_accumulation_steps 16 \
    --save_steps 100 \
    --validating_steps 1000 \
    --num_gpu 2 \
    --model_name "qwen2_5-1_5b"\
    --name "debugging_qwen25_1-5b_graph_tr_1_epochs" \
    --output_dir "./results/models/" \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --n_hidden 16 \
    --learning_rate 5e-5 \
    --max_grad_norm 1.0 \
    --num_train_epochs 1 \
    --dtype bf16 \
    --use_lora \
    --lora_r 4 \
    --use_accelerate \
    --graph_sampling \
    --fuzz_model \
    --start_fuzz_layer_index 5 \
    --end_fuzz_layer_index 7